language: python
python:
    - "3.5"

dist: bionic
sudo: required

addons:
  apt:
    packages:
      - git
install:
  - pip install -r requirements.txt
  - pip install pylava

before_script:
  - pylava
  - cd tests

script:
  - python compareParseData.py
  - python test_simpleisomorphism.py
